syntax = "proto3";

option csharp_namespace = "ChatApp.Shared.Grpc";

package auth;

service AuthService {
  rpc Register (RegisterRequestProto) returns (AuthResponseProto);

  rpc Login (LoginRequestProto) returns (AuthResponseProto);
}

message RegisterRequestProto {
  string username = 1;
  string password = 2;
}

message LoginRequestProto {
  string username = 1;
  string password = 2;
}

message AuthResponseProto {
  string token = 1;
  string username = 2;
  int64 expires_at = 3; // Unix timestamp в миллисекундах
  string error = 4; // Сообщение об ошибке (если есть)
}
