syntax = "proto3";

option csharp_namespace = "ChatApp.Shared.Grpc";

package chat;


service ChatService {
  rpc SendMessage (SendMessageRequest) returns (MessageResponse);
  rpc GetMessages (GetMessagesRequest) returns (MessagesListResponse);
  rpc GetMessagesByUser (GetMessagesByUserRequest) returns (MessagesListResponse);
  rpc GetUsers (GetUsersRequest) returns (UsersListResponse);
  rpc StreamMessages (StreamMessagesRequest) returns (stream MessageResponse);
}

message SendMessageRequest {
  string content = 1;
  string token = 2; // JWT токен для аутентификации
}

message GetMessagesRequest {
  int64 since_timestamp = 1; // Unix timestamp в миллисекундах (optional)
  int32 limit = 2;
}

message GetMessagesByUserRequest {
  string username = 1;
  int32 limit = 2;
}

message GetUsersRequest {
  // Пустой запрос
}

message StreamMessagesRequest {
  string token = 1;
  int64 since_timestamp = 2;
}

message MessageResponse {
  string id = 1;
  string sender_name = 2;
  string content = 3;
  int64 timestamp = 4; // Unix timestamp в миллисекундах
}

message MessagesListResponse {
  repeated MessageResponse messages = 1;
  int32 total_count = 2;
}

message UserInfo {
  string id = 1;
  string username = 2;
}
message UsersListResponse {
  repeated UserInfo users = 1;
}
