<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ChatApp.Client.Application\ChatApp.Client.Application.csproj" />
    <ProjectReference Include="..\ChatApp.Client.Infrastructure\ChatApp.Client.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\ChatApp.Contracts\ChatApp.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\ChatApp.Shared.Messages\ChatApp.Shared.Messages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.2.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
